name: Build and Deploy LaTeX Document

permissions: write-all

on:
  push:
    paths:
      - '**.tex'
      - 'imgs/**'
      - '.github/**/*.yml'
      - 'diagrams/img/**'
      - '**.puml'
      - '**.bib'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            diagrams_src:
              - 'diagrams/src/**'
      
      - name: Compile Diagrams
        if: steps.changes.outputs.diagrams_src == 'true'
        shell: bash
        run: |
          docker run \
            -v ./diagrams/src:/src \
            -v ./diagrams/img:/img \
            ghcr.io/plantuml/plantuml /src -o /img

      - name: Restore TeX Live Cache
        uses: actions/cache/restore@v4
        with:
          path: |
            /usr/local/texlive
          key: texlive-${{ runner.os }}-${{ hashFiles('**/*.tex') }}
          
      - name: Setup System Dependencies
        uses: Syndelis/cache-apt-pkgs-action@f3b6f83545eae209de57d2bcdca870c646b557d7
        with:
          packages: texlive-full
          version: 1.0
          execute_install_scripts: true

      - name: Build Latex PDF and HTML
        shell: bash
        run: |
          mkdir ./public
          pdflatex -output-directory ./public ufsj-abntex2.tex
          make4ht --output-dir ./public ufsj-abntex2.tex "mathjax"
          mv public/ufsj-abntex2.html public/index.html

      - name: Save TeX Live Cache
        uses: actions/cache/save@v4
        with:
          path: |
            /usr/local/texlive
          key: texlive-${{ runner.os }}-${{ hashFiles('**/*.tex') }}
      
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update PDF
          branch: ${{ github.ref_name }}
          commit_user_name: actions-user
          commit_user_email: actions@github.com
          commit_author: actions-user <actions@github.com>
          file_pattern: 'ufsj-abntex2.pdf diagrams/img/**'

      - name: Publish HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
